images/urls.py
from django.urls import include, path
from . import views

app_name = 'images'

urlpatterns = [
  path('create/', views.image_create, name='create'),
  path('detail/<int:id>/<slug:slug>/', views.image_detail, name='detail'),
  path('like/', views.image_like, name='like'),
  path('', views.image_list, name='list'),
  path('ranking/', views.image_ranking, name='ranking'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
  path("admin/", admin.site.urls),
  path('account/', include('account.urls')),
  path('images/', include('images.urls', namespace='images')),
  path('social-auth/', include('social_django.urls', namespace='social')),
  path('__reload__/', include('django_browser_reload.urls')),
  path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

images/models.py
from django.utils.text import slugify
from django.conf import settings
from django.urls import reverse
from django.db import models


class Image(models.Model):
  user = models.ForeignKey(
    settings.AUTH_USER_MODEL,
    related_name='images_created',
    on_delete=models.CASCADE,
  )
  title = models.CharField(max_length=255)
  slug = models.SlugField(max_length=255, blank=True)
  url = models.URLField(max_length=2000)
  image = models.ImageField(upload_to='images/%Y/%m/%d')
  description = models.TextField(blank=True)
  created = models.DateField(auto_now_add=True)
  users_like = models.ManyToManyField(
    settings.AUTH_USER_MODEL,
    related_name='images_liked',
    blank=True,
  )
  total_likes = models.PositiveIntegerField(default=0)

  class Meta:
    indexes = [
      models.Index(fields=['-created']),
      models.Index(fields=['-total_likes']),
    ]
    ordering = ['-created']

  def save(self, *args, **kwargs):
    if not self.slug:
      self.slug = slugify(self.title)
    super().save(*args, **kwargs)

  def get_absolute_url(self):
    return reverse('images:detail', args=[self.id, self.slug])

  def __str__(self):
    return self.title

images/forms.py
from django import forms
from django.core.files.base import ContentFile
from django.utils.text import slugify
import requests
from social_django.strategy import ContentType
from .models import Image


class ImageCreateForm(forms.ModelForm):
  class Meta:
    model = Image
    fields = ['title', 'url', 'description']
    widgets = {
      'url': forms.HiddenInput,
    }

  def clean_url(self):
    url = self.cleaned_data['url']
    valid_extensions = ['jpg', 'jpeg', 'png']
    extension = url.rsplit('.', 1)[1].lower()
    if extension not in valid_extensions:
      raise forms.ValidationError('The given URL does not ' \
                                  'match valid image extensions.')
    return url

  def save(self, force_insert=False, force_update=False, commit=True):
    image = super().save(commit=False)
    image_url = self.cleaned_data['url']
    name = slugify(image.title)
    extension = image_url.rsplit('.', 1)[1].lower()
    image_name = f"{name}.{extension}"
    response = requests.get(image_url)
    image.image.save(image_name, ContentFile(response.content), save=False)

    if commit:
      image.save()

    return image

images/views.py
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.http import JsonResponse, HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import get_object_or_404
from django.shortcuts import render, redirect
from django.contrib import messages
from django.conf import settings
import redis
from actions.utils import create_action
from .forms import ImageCreateForm
from .models import Image

r = redis.Redis(
  host=settings.REDIS_HOST,
  port=settings.REDIS_PORT,
  db=settings.REDIS_DB,
)


@login_required
def image_list(request):
  images = Image.objects.all()
  paginator = Paginator(images, 8)
  page = request.GET.get('page')
  images_only = request.GET.get('images_only')
  try:
    images = paginator.page(page)
  except PageNotAnInteger:
    images = paginator.page(1)
  except EmptyPage:
    if images_only:
      return HttpResponse('')
    images = paginator.page(paginator.num_pages)
  if images_only:
    return render(
      request,
      'images/image/list_images.html',
      {
        'section': 'images',
        'images': images
      },
    )
  return render(
    request,
    'images/image/list.html',
    {
      'section': 'images',
      'images': images
    },
  )


@login_required
@require_POST
def image_like(request):
  image_id = request.POST.get('id')
  action = request.POST.get('action')
  if image_id and action:
    try:
      image = Image.objects.get(id=image_id)
      if action == 'like':
        image.users_like.add(request.user)
        create_action(request.user, 'likes', image)
      else:
        image.users_like.remove(request.user)
      return JsonResponse({'status': 'ok'})
    except Image.DoesNotExist:
      pass
  return JsonResponse({'status': 'error'})


def image_detail(request, id, slug):
  image = get_object_or_404(Image, id=id, slug=slug)
  total_views = r.incr(f'image:{image.id}:views')
  r.zincrby('image_ranking', 1, image.id)
  return render(request, 'images/image/detail.html', {
    'section': 'images',
    'image': image,
    'total_views': total_views,
  })


@login_required
def image_ranking(request):
  image_ranking = r.zrange('image_ranking', 0, -1, desc=True)[:10]
  image_ranking_ids = [int(id) for id in image_ranking]
  most_viewed = list(Image.objects.filter(id__in=image_ranking_ids))
  most_viewed.sort(key=lambda x: image_ranking_ids.index(x.id))
  return render(request, 'images/rating.html', {
    'section': 'images',
    'most_viewed': most_viewed,
  })


@login_required
def image_create(request):
  if request.method == 'POST':
    form = ImageCreateForm(data=request.POST)
    if form.is_valid():
      cd = form.cleaned_data
      new_image = form.save(commit=False)
      new_image.user = request.user
      new_image.save()
      create_action(request.user, 'bookmarked image', new_image)
      messages.success(request, 'Image added successfully')
      return redirect(new_image.get_absolute_url())
  else:
    form = ImageCreateForm(data=request.GET)

  return render(request, 'images/image/create.html', {'form': form, 'section': 'images'})

templates/images/image/create.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block title %}Bookmark an image{% endblock title %}

{% block content %}
<h1 class="text-center text-2xl text-green-600 ">Bookmark an image</h1>
<br>
<div class="bg-slate-800 rounded-2xl p-5 m-2 text-xl ">
  <div class="flex flex-wrap ">
  <img src="{{ request.GET.url }}" class="w-1/2 rounded-lg m-2">
  <form method="post">
    {% csrf_token %}
    <div class="text-teal-900">
      {{ form|crispy }}
    </div>
    <input type="submit" value="Bookmark it!" class="text-center bg-green-600 hover:bg-green-400 px-3 py-2 rounded-lg">
  </form>
</div>
</div>
{% endblock content %}

templates/images/image/detail.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %}{{ image.title }}{% endblock title %}

{% block content %}
  <h1 class="text-4xl text-green-500 text-center my-3">{{ image.title }}</h1>

  <div class="bg-slate-800 rounded-lg p-3 m-2 flex flex-wrap">

  <div class="basis-1/3 flex flex-wrap">
    <a href="{{ image.image.url }}" class="mx-auto rounded-lg">
        <img src="{% thumbnail image.image 200x0 quality=100 %}" >
    </a>
    {% comment %} <img src="{{ image.url }}" alt="{{ image.title }}" class="h-[40vh] relative mx-auto rounded-lg"> {% endcomment %}
  </div>

  <div class="mx-auto basis-2/3">
    <div class="flex flex-wrap flex-col">
          {% with total_likes=image.users_like.count users_like=image.users_like.all %}
            <span class="text-amber-500 bg-slate-600 px-3 py-2 m-2 mx-auto rounded-full">
              <div id="likes-count">{{ total_likes }} like{{ total_likes|pluralize }}</div>
            </span>
            <span class="text-amber-500 bg-slate-600 px-3 py-2 m-2 mx-auto rounded-full">
              <div>{{ total_views }} view{{ total_views|pluralize }}</div>
            </span>
            <a href="#" id="like" data-id="{{ image.id }}" data-action="{% if request.user in users_like %}un{% endif %}like" class="p-2 bg-red-500 mx-auto rounded-lg hover:bg-red-400">
              {% if request.user not in users_like %}
                Like
              {% else %}
                Unlike
              {% endif %}
            </a>
          {% endwith %}
        {{ image.description|linebreaks }}
    </div>
    <br>
    <div>
      {% for user in image.users_like.all %}
        <div class="bg-emerald-800 {% if forloop.counter0|divisibleby:"2" %}bg-blue-800{% endif %} p-2 m-2 flex flex-wrap w-full">
          {% if user.profile.photo %}
            <img src="{{ user.profile.photo.url }}" class="h-[5vh] rounded-full ">
          {% endif %}
          <p class="mx-auto place-self-center">{{ user.first_name }}</p>
        </div>
      {% empty %}
        <p class="text-xl text-amber-500">Nobody likes this image yet.</p>
      {% endfor %}
    </div>
  </div>

  </div>
{% endblock content %}

{% block domready %}
  const url = '{% url "images:like" %}'
  const options = {
    method: 'POST',
    headers: {'X-CSRFToken': csrftoken},
    mode: 'same-origin'
  }
  
  document.querySelector('#like').addEventListener('click', function(e) {
    e.preventDefault()
    const likeButton = this

    const formData = new FormData()
    formData.append('id', likeButton.dataset.id)
    formData.append('action', likeButton.dataset.action)
    options['body'] = formData

    fetch(url, options)
      .then(response => response.json())
      .then(data => {
        if (data['status'] === 'ok') {
          const previousAction = likeButton.dataset.action

          const action = previousAction === 'like' ? 'unlike' : 'like'
          likeButton.dataset.action = action
          likeButton.innerHTML = action

          const likeCount = document.querySelector('div#likes-count')
          const totalLikes = parseInt(likeCount.innerHTML)
          likeCount.innerHTML = previousAction === 'like' ? totalLikes + 1 : totalLikes - 1
        }
      })

  })
{% endblock domready %}

templates/images/image/list.html
{% extends "base.html" %}

{% block title %}Images bookmarked{% endblock title %}

{% block content %}
<h1 class="text-4xl text-green-500 text-center my-3">{{ image.title }}</h1>

<div id="image-list" class="bg-slate-800 rounded-lg p-3 m-2 flex flex-wrap">
  {% include "images/image/list_images.html" %}
</div>
{% endblock content %}

{% block domready %}
  let page = 1
  let emptyPage = false
  let blockRequest = false

  window.addEventListener('scroll', function(e) {
    const margin = document.body.clientHeight - window.innerHeight - 200
    if (window.pageYOffset > margin && !emptyPage && !blockRequest) {
      blockRequest = true
      page += 1

      fetch('?images_only=1&page=' + page)
        .then(response => response.text())
        .then(html => {
          if (html === '') {
            emptyPage = true
          } else {
            let imageList = document.getElementById('image-list')
            imageList.insertAdjacentHTML('beforeEnd', html)
            blockRequest = false
          }
        })
    }
  })

  const scrollEvent = new Event('scroll')
  window.dispatchEvent(scrollEvent)
{% endblock domready %}

templates/images/image/list_images.html
{% load thumbnail %}


{% for image in images %}
  <div class="w-[300px] h-[400px] bg-blue-500 m-2 text-center hover:shadow-lg hover:shadow-red-500">
    
    <a href="{{ image.get_absolute_url }}" >
      {% thumbnail image.image 300x300 crop="smart" as im %}
      <a href="{{ image.get_absolute_url }}">
        <img src="{{ im.url }}" class="mx-auto">
      </a>
    </a>
    <div>
      <a href="{{ image.get_absolute_url }}" class="px-1 ">
        {{ image.title }}
      </a>
    </div>
  </div>
{% endfor %}